spring:
  devtools:
    #livereload:
    # enabled: true
    restart:
      enabled: true
      # classloader加载会更改的类
      additional-exclude: src/main/java
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bs-mysql:3306/bs_monitor?characterEncoding=utf-8&characterSetResults=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: parking
    password: BSzn@1999@2022
  data:
    redis:
      password: open_cloud_test_1
# xxl-job 定时任务配置
xxl:
  job:
    admin:
      # 多个地址使用,分割
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: xxl-job-executor-${spring.application.name}
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

# 文件配置
file:
  upload:
    file-path: /home/park/logs/monitor
    down-path: http://192.168.10.11:90/monitor/static
    jar-path: /home/park/docker
