spring:
  devtools:
    #livereload:
    # enabled: true
    restart:
      enabled: true
      # classloader加载会更改的类
      additional-exclude: src/main/java
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bs-mysql:3306/bs_monitor?characterEncoding=utf-8&characterSetResults=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: parking
    password: BSzn@1999@2022
  data:
    redis:
      password: baisheng123
# 文件配置
file:
  upload:
    down-path: http://192.168.10.11:90/monitor/static

security:
  ignore-paths:
    - "/**"
