version: '3'
services:
  bs-monitor:
    build:
      context: ${contextPath}/docker/${bsMonitor}/
      dockerfile: ./Dockerfile
      args:
        contextPath: ${contextPath}
        profileActive: ${profileActive}
    ports:
      - 8989:8989
    extra_hosts:
      bs-nacos: ${bsNacos}
      bs-mysql: ${bsMysql}
      bs-redis: ${bsRedis}
      bs-rabbitmq: ${monitorRabbitmq}
    container_name: ${bsMonitor}
    network_mode: "host"
    hostname: ${bsMonitor}
    image: ${bsMonitor}
    restart: always
    volumes:
      - ${logPath}/${bsMonitor}:${logPath}
      - ${contextPath}/docker/config:${contextPath}/config
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    logging:
      driver: json-file
      options:
        max-size: "1024m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 200M
  monitor-collector:
    build:
      context: ${contextPath}/docker/monitor-collector/
      dockerfile: ./Dockerfile
      args:
        contextPath: ${contextPath}
        profileActive: ${profileActive}
    ports:
      - 9999:9999
    extra_hosts:
      bs-nacos: ${bsNacos}
      bs-mysql: ${bsMysql}
      bs-redis: ${bsRedis}
      bs-rabbitmq: ${monitorRabbitmq}
    container_name: monitor-collector
    network_mode: "host"
    hostname: monitor-collector
    image: monitor-collector
    restart: always
    volumes:
      - ${logPath}/monitor-collector:${logPath}
      - ${contextPath}/docker/config:${contextPath}/config
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    logging:
      driver: json-file
      options:
        max-size: "1024m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 200M