server:
  port: 9999
  servlet:
    session:
      timeout: 120m
    context-path: /collector
#日志文件输出路径
logging:
  config: classpath:logback-nacos.xml
  level:
    com.cloud: info
    com.alibaba.boot.nacos: info
mybatis-plus:
  global-config:
    sql-parser-cache: true
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-handlers-package: com.cloud.collector.mybatis
tenant:
  open: true
  ignoreTables: [ 'charge_type','sys_province','sync_task','third_config' ]
# 数据库 相关设置
spring:
  main:
    #开启快速启动模式
    lazy-initialization: false
    allow-circular-references: true
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  application:
    name: ops-collector
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bs-mysql:3306/bs_monitor?characterEncoding=utf-8&characterSetResults=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: parking
    password: BSzn@1999@2022
    druid:
      query-timeout: 3000
      max-active: 1000
  data:
    redis:
      database: 9
      host: bs-redis
      port: 6379
      password: baisheng123
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
  rabbitmq:
    host: bs-rabbitmq
    port: 5672
    username: baisheng
    password: baisheng123
    virtual-host: bs_monitor
    listener:
      simple:
        acknowledge-mode: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    cache: false
#Mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


web:
  rootPath: 'd://image//car-snap/'
  pathPatterns: '/car-snap/**'
  excludePathPatterns:
    - '/static/**'
    - '/sysUser/login'
    - '/sysUser/all'
    - '/sysUser/refreshToken'
    - '/index/*'
    - '/lcd/*'

#自定义配置参数
base:
  #登陆账号admin的密码
  admindPwd: 111111
  #通信token，agent端和此保持一致
  agentToken: monitorToken
  #是否开启公众看板，yes开启，no关闭，公众看板页面无需登陆
  dashView: yes
  #数据表监控间隔,单位毫秒，默认60分钟
  dbTableTimes: 3600000
  #服务接口监控间隔，单位毫秒，默认10分钟
  heathTimes: 600000
  serverUrl: http://localhost:8989

#告警配置
mail:
  #告警邮件总开关，yes开启，no关闭
  allWarnMail: yes
  #监控主机内存使用率%报警值，超过此值即发送邮件报警
  memWarnVal: 98
  #监控主机cpu使用率%报警值，超过此值即发送邮件报警
  cpuWarnVal: 98
  #内存告警邮件开关，yes开启，no关闭。总开关开启后，此处设置才会生效。以下开关均遵循此规则。
  memWarnMail: yes
  #CPU告警邮件开关，yes开启，no关闭
  cpuWarnMail: yes
  #主机下线告警邮件开关，yes开启，no关闭
  hostDownWarnMail: yes
  #进程下线告警邮件开关，yes开启，no关闭
  appDownWarnMail: yes
  #服务接口告警邮件开关，yes开启，no关闭
  heathWarnMail: yes
nacos:
  config:
    username: bszn
    password: nacos
    server-addr: bs-nacos:8848
    # Nacos Server 控制台上下文路径，默认是 nacos，客户端默认为空会导致登录 404
    context-path: /nacos
    encode: UTF-8
    #配置自动刷新
    refresh-enabled: true
    data-id: ${spring.application.name}.yaml
    type: yaml
    auto-refresh: true
    group: DEFAULT_GROUP
    #是否开启Nacos配置预加载
    bootstrap:
      enable: true
      log-enable: true