spring:
  web:
    resources:
      # 添加自定义静态资源路径
      static-locations:
        - file:D:/home/park/logs/monitor/
      static-path-pattern: /static/**
  devtools:
    #livereload:
    # enabled: true
    restart:
      enabled: true
      # classloader加载会更改的类
      additional-exclude: src/main/java
# 文件配置
file:
  upload:
    down-path: http://$ip:8989/static
python:
  path: D:\app\miniconda3\python
  script: D:\Users\liuyun\IdeaProjects\py-sync\bs
  url: http://localhost:8989
logging:
  config: classpath:logback.xml
#security:
#  ignore-paths:
#    - "/**"